services:
  lorepaint:
    build:
      dockerfile: Dockerfile
      target: production
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
    environment:
      - LORE_PAINT_DB_HOST=${LORE_PAINT_DB_HOST}
      - LORE_PAINT_DB_NAME=${LORE_PAINT_DB_NAME}
      - LORE_PAINT_DB_PASSWORD=${LORE_PAINT_DB_PASSWORD}
      - LORE_PAINT_DB_PORT=${LORE_PAINT_DB_PORT}
      - LORE_PAINT_DB_USER=${LORE_PAINT_DB_USER}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-prod}
      - FRONT_URL=${FRONT_URL}
      - AI_URL=${AI_URL}
      - AI_MODEL=${AI_MODEL}
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_PASSWORD: ${LORE_PAINT_DB_PASSWORD}
      POSTGRES_USER: ${LORE_PAINT_DB_USER}
      POSTGRES_DB: ${LORE_PAINT_DB_NAME}
    volumes:
      - ./db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${LORE_PAINT_DB_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
  #    depends_on:
  #      - db
